#!/usr/bin/env bash
# Fix the container to run nginx as the nginx user on port 8080
apt-get install -y nginx > /dev/null 2>&1
sed -i 's/^user www-data/user nginx/' /etc/nginx/nginx.conf
sed -i 's/listen \(\[::\]:\)\?80\b/listen \18080/g' /etc/nginx/sites-enabled/default
chown -R nginx /var/log/nginx
nginx -s stop 2>/dev/null
nginx
