#!/usr/bin/env bash
# Debugged web stack 0 container

apt-get update -y
apt-get install -y apache2

echo "Hello Holberton" > /var/www/html/index.html
echo "ServerName localhost" >> /etc/apache2/apache2.conf

service apache2 start
