#!/usr/bin/env bash
# Configures Nginx with a 301 redirect on /redirect_me

sudo apt-get update -y
sudo apt-get install -y nginx

# Set the default page content
echo "Holberton School for the win!" | sudo tee /var/www/html/index.html > /dev/null

sudo sed -i '/server_name _;/a \\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}' /etc/nginx/sites-available/default

sudo service nginx restart
