#!/usr/bin/env bash
# Configures Nginx with a custom 404 page

sudo apt-get update -y
sudo apt-get install -y nginx

echo "Holberton School for the win!" | sudo tee /var/www/html/index.html > /dev/null

echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html > /dev/null

# Add redirect rule and custom 404 to the default nginx server block
sudo sed -i '/server_name _;/a \\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n\n\terror_page 404 /404.html;\n\tlocation = /404.html {\n\t\tinternal;\n\t}' /etc/nginx/sites-available/default

sudo service nginx restart
